### ISSUE TITLE
Potential security vulnerability in one of our dependencies

### ISSUE THREAD

**Issue by Agri** [carldata/anomaly-tool#81]
I've investigated the problem a little bit and after some searching in package-lock.json it seems that infamous "hoek": "2.16.3" is very nested dependency of watchpack which is a part of webpack. This tree dependencies looks like this:

Path: webpack >> watchpack@1.4.0>>chokidar@1.7.0>>fsevents@1.1.3>>node-pre-gyp@0.6.39>>hawk>>hoek

It seems that guys from hoek fixed the vulnerability issue, but other packages that use this package in webpack should be updated to have this change. After some research I found that this issue is still not closed in webpack:

https://github.com/webpack/watchpack/issues/63

So I think there are two solutions:

1. Just wait till webpack fixes it .
2. Try to downgrade version of webpack and see it that fixes the problem, but not below webpack version 4.0.0 because I think our webpack configs would not work with older version.

Personally I would go with the first option because project is still in early stage of development and I don't think it's very unsafe. Even though this webpack issue is still open since February.

**Comment by tpichlak** [comment]
Another thing if we decide to go path in option 2, then we could use part of auto-i-and-i package.json which does not shown any problem with vulnerabilities. The packages of webpack are there in fixed versions like this:

 "webpack": "4.1.1",
 "webpack-cli": "2.0.12",
 "webpack-dev-server": "3.1.1",
 "webpack-merge": "4.1.2"
